layout_spectrum: 0.1484224
typography_spectrum: 0.5293037
color:
  saturation: 0.4819067
  lightness: 0.7739336
  brandStrength: 0.1263896
  rhythmicContrast: 0.2982791
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: NUTIDEN
